version: "3"

services:

  zoopkeeper-pubsub:
    image: bitnami/zookeeper:3.8.2
    container_name: zookeeper-pubsub
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka-pubsub:
    image: bitnami/kafka:3.5.0
    container_name: kafka-pubsub
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-pubsub:2181
      ALLOW_PLAINTEXT_LISTENER: yes




